# Generated by Django 4.0.1 on 2022-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0005_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='plataform.OrderItem'),
        ),
    ]
