# Generated by Django 4.0.1 on 2022-05-18 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0008_remove_orderitem_item_remove_orderitem_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pills',
            name='images',
        ),
        migrations.AddField(
            model_name='pills',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
